spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  web:
    resources:
      add-mappings: true # 정적 리소스 매핑 활성화
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    rest:
      uris: https://localhost:9200
      username: elastic
      password: ${ELASTIC_PASSWORD}
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        verification-mode: none  # SSL 검증 비활성화
        key-store: ./src/main/resources/springboot.p12  # Keystore 경로
        key-store-password: ${KEYSTORE_PASSWORD}       # Keystore 비밀번호
        key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  web:
    resources:
      add-mappings: true # 정적 리소스 매핑 활성화
  kafka:
    bootstrap-servers: kafka:9092
  elasticsearch:
    rest:
      uris: https://elasticsearch:9200
      username: elastic
      password: ${ELASTIC_PASSWORD}
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        verification-mode: none  # SSL 검증 비활성화
        key-store: /app/springboot.p12  # Keystore 경로
        key-store-password: ${KEYSTORE_PASSWORD}       # Keystore 비밀번호
        key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 성능 최적화를 위해 false로 설정
  logging:
    level:
      org.springframework.data.elasticsearch.client.WIRE: TRACE
      org.springframework.data.elasticsearch: DEBUG
      org.elasticsearch: DEBUG

server:
  port: 443
  ssl:
    enabled: true
    key-store: /app/springboot.p12  # Keystore 경로
    key-store-password: ${KEYSTORE_PASSWORD}  # Keystore 비밀번호
    key-store-type: PKCS12
    key-alias: projectkkk2
  security:
    require-ssl: false
  hsts:
    enabled: false
