spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: https://localhost:9200
    username: elastic
    password: Ccenter123456!
    ssl:
      verification-mode: certificate
      key-store: ./keystore.p12
      key-store-password: changeit
      key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true
  server:
    ssl:
      key-store: ./keystore.p12
      key-store-password: changeit
      key-store-type: PKCS12
      key-alias: tomcat
      enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
  elasticsearch:
    uris: https://elasticsearch:9200
    username: elastic
    password: Ccenter123456!
    connection-timeout: 60s
    socket-timeout: 30s
    ssl:
      verification-mode: certificate
      key-store: /app/keystore.p12
      key-store-password: changeit
      key-store-type: PKCS12
  data:
    elasticsearch:
      repositories:
        enabled: true
  server:
    ssl:
      key-store: /app/keystore.p12
      key-store-password: changeit
      key-store-type: PKCS12
      key-alias: tomcat
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  logging:
    level:
      org.springframework.data.elasticsearch.client.WIRE: TRACE
      org.springframework.data.elasticsearch: DEBUG
      org.elasticsearch: DEBUG
      javax.net.ssl: DEBUG  # SSL 디버깅을 위한 로깅 추가