spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch: # data.elasticsearch 대신 elasticsearch 사용
    uris: https://localhost:9200
    username: elastic
    password: Ccenter123456!
    ssl:
      verification-mode: certificate
      certificate-authorities: ./elasticsearch.crt
  data:
    elasticsearch:
      repositories:
        enabled: true

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
  elasticsearch:
    uris: https://elasticsearch:9200
    username: elastic
    password: Ccenter123456!
    connection-timeout: 60s
    socket-timeout: 30s
    ssl:
      verification-mode: certificate
      certificate-authorities: /app/elasticsearch.crt
  data:
    elasticsearch:
      repositories:
        enabled: true
  server:
    ssl:
      key-store: /app/keystore.jks
      key-store-password: changeit
      key-store-type: JKS
      key-alias: tomcat
      enabled: true # SSL 활성화 추가
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false # 성능 최적화를 위해 false로 설정
  logging:
    level:
      org.springframework.data.elasticsearch.client.WIRE: TRACE
      org.springframework.data.elasticsearch: DEBUG
      org.elasticsearch: DEBUG