# application.yml
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
  server:
    ssl:
      key-store: file:/app/keystore.jks    # 도커 환경용 경로만 변경
      key-store-password: changeit         # 기존 비밀번호 유지
      key-store-type: JKS
      key-alias: tomcat